### ISSUE TITLE
Can not pip install  Intelligent-Scissors correctly in python3.8.0

### ISSUE THREAD

**Issue by Applied-Energetic** [stanislaushimovolos/Intelligent-Scissors#6]
## Can not pip install  Intelligent-Scissors correctly in python3.8.0
python:3.8.0
env:windows
editor:pycharm community
---
pip install intelligent-scissors
Looking in indexes: http://pypi.douban.com/simple
Collecting intelligent-scissors
  Downloading http://pypi.doubanio.com/packages/8e/d0/6d2a734596193ed5f6de041683f5d545bbf592080309fa0ef450a960fff9/intelligent-scissors-2.0.tar.gz (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.0/118.0 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error                 
                                                      
  × python setup.py egg_info did not run successfully.
  │ exit code: 1                                      
  ╰─> [6 lines of output]                             
      Traceback (most recent call last):              
        File "<string>", line 2, in <module>          
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Xiayue\AppData\Local\Temp\pip-install-zslb1f1s\intelligent-scissors_adcc8dee390548839ff8303d4a6aac1b\setup.py", line 13, in <module>
          long_description = fh.read()
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 2837: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

---

**Comment by Applied-Energetic** [comment]
Successful installation by  modifying the file setup.py in intelligent-scissors-2.0.tar.gz

add "encoding='utf-8'"

import setuptools
from scissors import __version__

from Cython.Distutils import build_ext
import numpy as np

extensions = [
    setuptools.Extension("scissors.search", ["scissors/search.pyx"],
                         include_dirs=[np.get_include()], language='c++'),
]

with open('README.md', 'r', **encoding='utf-8'**) as fh:
    long_description = fh.read()

with open('requirements.txt', encoding='utf-8') as file:
    requirements = file.read().splitlines()

setuptools.setup(
    include_package_data=True,
    name='intelligent-scissors',
    version=__version__,
    author="Stanislav Shimovolos",
    author_email='shimovolos.sa@phystech.edu',
    description="Intelligent Scissors tool",
    long_description=long_description,
    long_description_content_type='text/markdown',
    license='MIT',
    url='https://github.com/stanislaushimovolos/Intelligent-Scissors',
    download_url='https://github.com/stanislaushimovolos/Intelligent-Scissors/v%s.tar.gz' % __version__,
    packages=['scissors'],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    install_requires=requirements,
    python_requires='>=3.5',
    cmdclass={'build_ext': build_ext},
    ext_modules=extensions,
    package_data={'scissors': ['*.pyx']},
)
